<?php

declare(strict_types=1);

namespace Mnb\ScraperKit\Search;

final class SearchProviderRegistry
{
    public const VERSION = '1.0.2';

    /** @return array<string,array<string,mixed>> */
    public static function providers(): array
    {
        return [
            'offline' => [
                'id' => 'offline',
                'name' => 'Offline/manual search result importer',
                'configured' => true,
                'requires_network' => false,
                'requires_api_key' => false,
                'env' => [],
                'notes' => 'Always available. Import JSON search results or seed URLs generated by approved internal workflows.',
            ],
            'google_custom_search' => [
                'id' => 'google_custom_search',
                'aliases' => ['google', 'google_cse'],
                'name' => 'Google Programmable Search / Custom Search JSON API',
                'configured' => self::env('GOOGLE_CUSTOM_SEARCH_API_KEY') !== '' && self::env('GOOGLE_CUSTOM_SEARCH_ENGINE_ID') !== '',
                'requires_network' => true,
                'requires_api_key' => true,
                'env' => ['GOOGLE_CUSTOM_SEARCH_API_KEY', 'GOOGLE_CUSTOM_SEARCH_ENGINE_ID'],
                'notes' => 'API-first web search connector. Do not scrape Google results pages directly.',
            ],
            'azure_bing_grounding' => [
                'id' => 'azure_bing_grounding',
                'aliases' => ['bing', 'azure_bing'],
                'name' => 'Azure/Bing grounding-style provider slot',
                'configured' => self::env('AZURE_BING_SEARCH_KEY') !== '' || self::env('AZURE_AI_SEARCH_KEY') !== '',
                'requires_network' => true,
                'requires_api_key' => true,
                'env' => ['AZURE_BING_SEARCH_KEY', 'AZURE_AI_SEARCH_KEY', 'AZURE_BING_ENDPOINT'],
                'notes' => 'Provider slot for approved Bing/Azure search workflows. Legacy results-page scraping is intentionally unsupported.',
            ],
            'serpapi' => [
                'id' => 'serpapi',
                'name' => 'SerpAPI-compatible provider slot',
                'configured' => self::env('SERPAPI_KEY') !== '',
                'requires_network' => true,
                'requires_api_key' => true,
                'env' => ['SERPAPI_KEY'],
                'notes' => 'Optional paid provider slot for teams already approved to use SERP APIs.',
            ],
        ];
    }

    /** @return array<string,mixed> */
    public static function summary(): array
    {
        $providers = self::providers();
        return [
            'search_version' => self::VERSION,
            'default_provider' => 'offline',
            'providers_total' => count($providers),
            'configured_total' => count(array_filter($providers, static fn(array $p): bool => (bool) ($p['configured'] ?? false))),
            'providers' => array_values($providers),
            'policy' => [
                'do_not_scrape_search_result_pages' => true,
                'use_official_or_approved_search_apis' => true,
                'store_search_query_and_provider_audit' => true,
                'respect_target_site_robots_after_discovery' => true,
            ],
        ];
    }

    public static function canonical(string $provider): string
    {
        $provider = strtolower(trim($provider));
        foreach (self::providers() as $id => $meta) {
            if ($provider === $id || in_array($provider, (array) ($meta['aliases'] ?? []), true)) {
                return $id;
            }
        }
        return $provider !== '' ? $provider : 'offline';
    }

    private static function env(string $name): string
    {
        $value = getenv($name);
        return is_string($value) ? trim($value) : '';
    }
}
