<?php

declare(strict_types=1);

namespace Mnb\ScraperKit\Console;

/**
 * Central command metadata for the Symfony Console front end.
 */
final class CommandRegistry
{
    /** @return array<string,string> command name => description */
    public static function commands(): array
    {
        return [
            'crawl' => 'Crawl one URL/site with safety rules, presets, common data, optional browser fallback, and optional professional pipeline.',
            'hardening:doctor' => 'Run production-readiness checks for CI, command contracts, release hygiene, optional runtimes, and compatibility posture.',
            'ci:check' => 'Run strict repo/CI checks without failing on locally installed vendor/ or ignored storage.',
            'release:check' => 'Run strict final archive checks: no vendor, .git, composer.lock, or generated storage outputs.',
            'benchmark:run' => 'Run deterministic local micro-benchmarks for URL normalization, safety checks, JSON handling, and command metadata.',
            'compat:commands' => 'Show or validate the public command/option compatibility contract for backward-compatible releases.',
            'browser:test' => 'Diagnose browser fallback need and optionally render one URL with the optional browser adapter.',
            'browser:session-create' => 'Create an allowed-domain browser session profile for authorized login workflows.',
            'browser:session-list' => 'List browser session profiles and cookie/session files.',
            'browser:session-show' => 'Show one browser session profile.',
            'browser:session-clear' => 'Clear browser session cookies/artifacts, optionally removing the profile.',
            'browser:session-test' => 'Test an authorized browser session against an allowed URL.',
            'browser:login' => 'Prepare manual login assist instructions and optional browser render for an authorized session.',
            'distributed:doctor' => 'Inspect distributed queue capability, Redis availability, selected adapter, and worker settings.',
            'distributed:status' => 'Show distributed queue counts, leases, completed jobs, failed jobs, namespace, and worker group.',
            'distributed:enqueue' => 'Enqueue one command payload into the distributed queue.',
            'distributed:reserve' => 'Reserve one distributed job for debugging and worker integration tests.',
            'distributed:ack' => 'Acknowledge a reserved distributed job as completed.',
            'distributed:fail' => 'Mark a reserved distributed job as failed.',
            'distributed:heartbeat' => 'Refresh a distributed job lease heartbeat.',
            'distributed:purge' => 'Purge distributed queue state, usually with --force in test/dev environments.',
            'worker:distributed' => 'Run a distributed worker loop using Redis when available or the file adapter fallback.',
            'db:init' => 'Initialize SQLite/MySQL storage tables for jobs, pages, records, failures, validation issues, and exports.',
            'db:test' => 'Test database connection settings and show the detected PDO driver.',
            'db:status' => 'Show database table row counts.',
            'db:save-crawl' => 'Save crawl JSON pages to the database storage layer.',
            'db:save-pipeline' => 'Save pipeline records and validation issues to database storage.',
            'db:export' => 'Export supported database storage table rows as JSON or CSV.',
            'retry:plan' => 'Create safe retry plans with backoff decisions for crawl failures or failed jobs.',
            'schedule:create' => 'Create a local schedule that enqueues a ScraperKit job when due.',
            'schedule:list' => 'List local schedules and due status.',
            'schedule:show' => 'Show one local schedule JSON file.',
            'schedule:run-due' => 'Enqueue all due schedules into the local job queue.',
            'schedule:enable' => 'Enable one local schedule.',
            'schedule:disable' => 'Disable one local schedule.',
            'monitor:summary' => 'Show queue, schedule, lock, and health monitoring summary.',
            'monitor:stale-locks' => 'Report stale worker locks that need attention.',
            'plugin:list' => 'List installed and bundled config-only plugins.',
            'plugin:show' => 'Show one plugin manifest with resolved assets.',
            'plugin:validate' => 'Validate a plugin manifest and referenced assets.',
            'plugin:install' => 'Install a plugin into storage/plugins.',
            'plugin:enable' => 'Enable an installed plugin manifest.',
            'plugin:disable' => 'Disable an installed plugin manifest.',
            'plugin:doctor' => 'Validate all discovered plugins and report issues.',
            'api:routes' => 'List lightweight JSON API routes for local dashboards and automation.',
            'api:token' => 'Generate a local API Bearer token for api:serve.',
            'api:serve' => 'Serve the optional lightweight JSON API using PHP built-in server.',
            'dashboard:status' => 'Show dashboard health, URLs, and read-only data availability.',
            'dashboard:build' => 'Build a static HTML dashboard snapshot from local queue/schedule/plugin/profile data.',
            'dashboard:serve' => 'Serve the optional local HTML admin dashboard using PHP built-in server.',
            'dataset:create' => 'Create a versioned dataset snapshot from crawl, pipeline, source, intelligence, or URL-list data.',
            'dataset:list' => 'List local dataset snapshots from storage/datasets.',
            'dataset:show' => 'Show one dataset manifest and quality summary.',
            'dataset:diff' => 'Compare two dataset snapshots and report added, removed, changed, and common records.',
            'dataset:export' => 'Export normalized dataset records as JSON, CSV, or JSONL.',
            'annotation:init' => 'Initialize an annotation file for review labels and future ML training.',
            'annotation:add' => 'Add one review annotation to a dataset annotation file.',
            'eval:dataset' => 'Evaluate dataset completeness, validation, duplicates, annotations, and training readiness.',
            'eval:pipeline' => 'Evaluate pipeline records without first creating a dataset snapshot.',
            'eval:profile' => 'Evaluate profile schema field success against a dataset.',
            'eval:selectors' => 'Measure selector/field success for a profile against a dataset.',
            'benchmark:profile' => 'Benchmark a profile against dataset records.',
            'benchmark:compare' => 'Compare evaluation metrics between two datasets.',
            'annotation:stats' => 'Show label counts, field counts, and annotation coverage.',
            'annotation:coverage' => 'Show annotation coverage for one dataset.',
            'annotation:export' => 'Export annotation rows for review or ML workflows.',
            'intelligence:doctor' => 'Show ML/intelligence capability status and optional PHP-ML availability.',
            'intelligence:analyze' => 'Extract ML-ready features from crawl, pipeline, source, or URL JSON files.',
            'intelligence:classify' => 'Classify pages into article/ecommerce/job/tender/contact/JS/error groups.',
            'intelligence:quality' => 'Predict page/record quality labels from extracted features.',
            'intelligence:priority' => 'Score and sort URLs for crawl priority from TXT or JSON input.',
            'intelligence:selectors' => 'Suggest profile-aware CSS/meta selectors from saved HTML.',
            'webhook:list' => 'List webhook endpoints from config/webhooks.json or a custom config file.',
            'webhook:test' => 'Create or send a test webhook event.',
            'webhook:send' => 'Send one JSON payload as a webhook event to an endpoint.',
            'http:test' => 'Test the HTTP engine, redirects, headers, and challenge/protection detection.',
            'bulk:crawl' => 'Crawl a URL list with gaps, pauses, checkpoint state, and resume support.',
            'url:process' => 'Process URLs sequentially with retry, method ladder, backoff, checkpoint, and resume.',
            'robots:test' => 'Inspect robots.txt decision for one URL.',
            'encoding:test' => 'Fetch one URL and report detected/converted encoding.',
            'common:extract' => 'Extract common structured data patterns from one URL.',
            'common:types' => 'List supported common data types and extraction profiles.',
            'rule:analyze' => 'Analyze saved HTML or one URL and report signals for profile/rule generation.',
            'rule:generate' => 'Generate starter profile schemas from HTML with the auto-profile assistant.',
            'rule:test' => 'Test generated or existing rules against a saved HTML sample.',
            'rule:doctor' => 'Check profile schemas, extraction rules, and optional sample output quality.',
            'profile:scaffold' => 'Scaffold a new profile schema template without writing PHP code.',
            'profile:list' => 'List available profile schema files.',
            'profile:show' => 'Show one profile schema.',
            'profile:validate' => 'Validate one profile schema JSON file.',
            'extract:rules' => 'Extract fields from one URL using profile schema rules or custom rule options.',
            'extract:types' => 'List extraction output types: links, text, HTML, images, PDFs, tables, lists, headings, components, patterns, and dictionary.',
            'extract:components' => 'Extract common page components and repeated element groups from saved HTML or one URL.',
            'extract:options' => 'Run configurable extraction options including selectors, HTML modes, asset filters, patterns, and dictionary learning.',
            'extract:dictionary' => 'Learn new words from extracted text into a reusable word dictionary.',
            'extract:patterns' => 'List or run registered regex extraction patterns.',
            'extract:mappings' => 'List or apply reusable source-to-target data mappings.',
            'job:create' => 'Create a local queued crawl/source job JSON file.',
            'job:list' => 'List queued jobs across queue states.',
            'job:show' => 'Show one queued job manifest.',
            'job:pause' => 'Pause one queued job.',
            'job:resume' => 'Resume one paused/failed/cancelled queued job.',
            'job:cancel' => 'Cancel one queued job.',
            'worker:once' => 'Run one pending queued job and exit.',
            'worker:run' => 'Run a queue worker loop.',
            'worker:status' => 'Show queue counts and active worker locks.',
            'queue:failed' => 'List failed queue jobs.',
            'queue:retry' => 'Retry one failed queue job.',
            'queue:retry-safe' => 'Retry only failed queue jobs that pass the safe retry policy.',
            'queue:retry-all' => 'Retry all failed queue jobs.',
            'queue:clear-failed' => 'Clear failed queue job files.',
            'report:failed' => 'Create failed/skipped URL diagnostics from crawl JSON.',
            'export:failed' => 'Export failed/skipped URL diagnostics as JSON, CSV, or XML.',
            'report:summary' => 'Generate professional job summary reports as HTML, JSON, CSV, or XML.',
            'bundle:create' => 'Create a ZIP bundle containing exports, reports, manifests, and logs.',
            'pipeline:run' => 'Run the professional crawl pipeline on crawl JSON.',
            'retry:failed' => 'Create a retry URL list from failed crawl pages.',
            'export:records' => 'Export pipeline records to JSON, CSV, XML, or HTML.',
            'export:validation' => 'Export validation issues from pipeline output as JSON, CSV, or XML.',
            'export:connector-list' => 'List configured export delivery connectors for local folders and webhook automation.',
            'export:connector-show' => 'Show one export connector configuration.',
            'export:connector-validate' => 'Validate export connector configuration.',
            'export:connector-test' => 'Dry-run an export connector delivery with a generated sample artifact.',
            'export:deliver' => 'Deliver selected export/report/dataset files through a configured connector.',
            'export:manifest' => 'Build a checksum manifest for selected export artifacts.',
            'template:list' => 'List bundled project templates for common crawl/extract/report workflows.',
            'template:show' => 'Show one project template manifest.',
            'template:validate' => 'Validate one project template manifest.',
            'template:create' => 'Create a ready-to-run project workspace from a template.',
            'preset:list' => 'List bundled preset packs that group profiles, templates, and workflow examples.',
            'preset:show' => 'Show one preset pack manifest.',
            'preset:validate' => 'Validate one preset pack manifest.',
            'preset:install' => 'Install one preset pack into a project folder.',
            'security:audit' => 'Run package/project security audit for release hygiene, secrets, configs, sessions, plugins, and public surfaces.',
            'security:doctor' => 'Show concise security posture summary and recommended release actions.',
            'security:secrets-scan' => 'Scan project files for common committed secret patterns before release.',
            'security:policy' => 'Write or show the responsible crawling and release compliance policy template.',
            'compliance:report' => 'Generate a JSON or HTML responsible crawling/compliance report from the security audit.',
            'enterprise:doctor' => 'Show v4 enterprise workspace/user/audit readiness summary.',
            'enterprise:roles' => 'Show built-in enterprise role capability map.',
            'workspace:create' => 'Create a local project workspace with optional owner and defaults.',
            'workspace:list' => 'List enterprise workspaces.',
            'workspace:show' => 'Show one enterprise workspace manifest.',
            'workspace:assign-user' => 'Assign a user to a workspace with a role.',
            'user:create' => 'Create a local enterprise user metadata record without storing passwords.',
            'user:list' => 'List local enterprise users.',
            'user:disable' => 'Disable a local enterprise user metadata record.',
            'audit:events' => 'List recent enterprise audit events.',
            'validate:records' => 'Validate records using required fields.',
            'job:summary' => 'Show job manifest, crawl summary, and pipeline summary.',
            'job:run' => 'Run one queued job by ID, or run a legacy JSON job configuration.',
            'source:discover' => 'Discover safer source candidates such as sitemap, feeds, robots, and well-known endpoints.',
            'source:sitemap' => 'Read sitemap.xml or sitemap index and export crawlable URLs.',
            'source:rss' => 'Read RSS/Atom feed and export normalized records/URLs.',
            'source:csv' => 'Read crawl URLs from CSV using a configurable URL column.',
            'source:json' => 'Read crawl URLs from JSON using a dot path such as items.*.url.',
            'source:api' => 'Fetch a JSON API endpoint and extract URLs using a dot path.',
            'source:urls' => 'Export a URL list from source connector JSON output.',
            'publisher:list' => 'List safe academic publisher metadata crawl targets and flexibility notes.',
            'publisher:show' => 'Show one academic publisher crawl profile, seed URLs, modes, and safety defaults.',
            'publisher:seeds' => 'Export academic publisher seed URLs as TXT, CSV, or JSON.',
            'publisher:plan' => 'Generate metadata-only crawl job plans for academic publisher seeds.',
            'publisher:graph' => 'Show publisher navigation graph from about/catalog pages to journals, books, issues, articles, and chapters.',
            'publisher:enterprise-plan' => 'Generate enterprise metadata crawl workflow steps for one publisher.',
            'publisher:extract-article' => 'Extract normalized article/chapter metadata from saved publisher HTML.',
            'publisher:schema' => 'Show or export the normalized article metadata schema.',
            'publisher:normalize' => 'Normalize source/API/feed/sitemap records into scholarly article metadata rows.',
            'plos:journals' => 'List known PLOS journals, API names, homepages, and feed candidates.',
            'plos:search' => 'Use the PLOS Search API and return normalized article records.',
            'plos:feed' => 'Fetch a PLOS journal RSS/Atom feed and normalize article records.',
            'plos:urls' => 'Export article/PDF/XML/DOI URLs from PLOS API results for bulk workflows.',
            'elsevier:journals' => 'Show Elsevier/ScienceDirect source connector catalog and API command hints.',
            'elsevier:search' => 'Search ScienceDirect API using an Elsevier API key.',
            'elsevier:metadata' => 'Fetch ScienceDirect article metadata by DOI or PII.',
            'elsevier:doi' => 'Shortcut for ScienceDirect article metadata by DOI.',
            'elsevier:serial' => 'Fetch Elsevier serial title metadata by ISSN.',
            'elsevier:urls' => 'Export article/DOI/API URLs from ScienceDirect search results.',
        ];
    }

    /** @return list<string> */
    /** @return list<string> */
    /** @return list<string> */
    public static function optionNames(): array
    {
        return [
            'allow-path',
            'api-base',
            'api-key',
            'api-key-in-query',
            'article-api-base',
            'attempts',
            'backoff',
            'backoff-multiplier',
            'batch-pause',
            'batch-size',
            'browser',
            'browser-auto',
            'browser-engine',
            'browser-mode',
            'browser-output-dir',
            'browser-profile',
            'browser-timeout-ms',
            'block-assets',
            'checkpoint',
            'common-data',
            'crawl',
            'common-profile',
            'common-type',
            'content',
            'url-column',
            'path',
            'max-sitemaps',
            'delimiter',
            'cookie-jar',
            'count',
            'dedupe-key',
            'delay',
            'delay-ms',
            'depth',
            'do-not-skip-challenge-pages',
            'do-not-skip-idp',
            'do-not-stop-on-challenge',
            'doi',
            'engine',
            'extract-preset',
            'fail-on-challenge',
            'force-browser',
            'feed-url',
            'field',
            'field-map',
            'fields',
            'format',
            'fallback-min-text',
            'fallback-required-field',
            'headless',
            'include-logs',
            'include-manifest',
            'fq',
            'gap',
            'gap-ms',
            'header',
            'http-engine',
            'id',
            'ignore-robots',
            'include-failed',
            'include-headers',
            'include-html',
            'include-page',
            'include-skipped',
            'inst-token',
            'insttoken',
            'issn',
            'job-dir',
            'journal',
            'json',
            'max',
            'max-attempts',
            'max-delay-seconds',
            'max-depth',
            'max-pages',
            'max-redirects',
            'max-runtime-seconds',
            'max-runtime',
            'max-jobs',
            'method',
            'methods',
            'min-quality',
            'network',
            'network-profile',
            'no-api-key-required',
            'no-browser-fallback',
            'no-cookie-jar',
            'no-preset-records',
            'no-robots',
            'no-verify-ssl',
            'only-type',
            'output',
            'output-dir',
            'pause-every-seconds',
            'pause-seconds',
            'pipeline',
            'render',
            'rendered-html',
            'pipeline-dedupe-key',
            'pipeline-field-map',
            'pipeline-format',
            'pipeline-include-failed',
            'pipeline-include-skipped',
            'pipeline-min-quality',
            'pipeline-output',
            'pipeline-profile',
            'pipeline-required-field',
            'preset',
            'base-url',
            'name',
            'profile-name',
            'profile',
            'profile-file',
            'profile-schema',
            'query',
            'required-field',
            'resume',
            'retry-challenge',
            'retry-delay',
            'retry-delay-seconds',
            'retry-status',
            'rows',
            'rule',
            'rules-file',
            'same-domain',
            'same-final-host',
            'save-body',
            'save-rendered-html',
            'screenshot',
            'serial-api-base',
            'skip-challenge-pages',
            'skip-final-host',
            'skip-identity-provider-final-urls',
            'skip-url',
            'solr',
            'sort',
            'start',
            'stay-under-start-path',
            'stop-file',
            'strip-final-param',
            'strip-final-url-query-params',
            'success-status',
            'timeout',
            'timeout-seconds',
            'viewport-width',
            'viewport-height',
            'database-url',
            'dsn',
            'sqlite',
            'db-user',
            'db-pass',
            'table',
            'limit',
            'wait-ms',
            'wait-selector',
            'wait-until',
            'type',
            'until-success',
            'use-cookie-jar',
            'user-agent',
            'continue-on-error',
            'file',
            'input',
            'job-id',
            'memory-limit',
            'queue-dir',
            'sleep',
            'source',
            'source-file',
            'source-url',
            'state',
            'stop-when-empty',
            'title',
            'worker-id',
            'view',
            'command',
            'arg',
            'schedule-id',
            'every-seconds',
            'every-minutes',
            'every-hours',
            'delay-seconds',
            'at',
            'max-runs',
            'dry-run',
            'failed-jobs',
            'all',
            'force',
            'stale-lock-ttl',
            'ttl-seconds',
            'plugin-dir',
            'plugin-id',
            'plugins-dir',
            'host',
            'port',
            'prefix',
            'print-command',
            'webhook-url',
            'webhook-header',
            'webhook-secret',
            'config',
            'payload',
            'model',
            'training-file',
            'features-file',
            'labels-file',
            'confidence',
            'threshold',
            'datasets-dir',
            'dataset-dir',
            'dataset-id',
            'record-id',
            'label',
            'note',
            'old',
            'new',
            'annotations',
            'user',
            'training-ready',
            'training-type',
            'evaluation-file',
            'annotations-file',
            'dataset',
            'compare-with',
            'dashboard-token',
            'recent',
            'refresh',
            'session',
            'browser-session',
            'domain',
            'domains',
            'login-url',
            'remove-profile',
            'timeout-ms',
            'no-headless',
            'allow-assets',
            'no-html',
            'once',
            'stop-on-error',
            'send',
            'distributed-adapter',
            'adapter',
            'redis-url',
            'namespace',
            'queue-name',
            'queue',
            'worker-group',
            'group',
            'visibility-timeout',
            'lease-seconds',
            'heartbeat-ttl',
            'lease-id',
            'distributed-dir',
            'payload-file',
            'message',
            'theme',
            'connector',
            'dir',
            'extension',
            'template',
            'pack',
            'project-name',
            'template-dir',
            'preset-dir',
            'allowed-extension',
            'policy',
            'fail-on-high',
            'workspace',
            'workspace-id',
            'description',
            'display-name',
            'owner',
            'actor',
            'role',
            'status',
            'active-only',
            'retention-days',
            'action',
            'publisher',
            'max-journals',
            'max-books',
            'max-issues',
            'max-articles',
            'url',
            'risk',
            'dictionary',
            'dictionary-file',
            'patterns',
            'patterns-file',
            'mappings',
            'mappings-file',
            'mapping',
            'types',
            'selector',
            'min-repeats',
            'min-length',
            'save-html',
            'whole-html',
            'html',
            'no-images',
            'strict',
            'mode',
            'iterations',
            'respect-robots',
            'validate',
        ];
    }

    /** @return list<string> */
    public static function valueLessOptions(): array
    {
        return [
            'api-key-in-query',
            'browser-auto',
            'block-assets',
            'common-data',
            'crawl',
            'do-not-skip-challenge-pages',
            'do-not-skip-idp',
            'do-not-stop-on-challenge',
            'fail-on-challenge',
            'force-browser',
            'ignore-robots',
            'include-failed',
            'include-headers',
            'include-html',
            'include-logs',
            'include-manifest',
            'include-page',
            'include-skipped',
            'json',
            'no-api-key-required',
            'no-browser-fallback',
            'no-cookie-jar',
            'no-preset-records',
            'no-robots',
            'no-verify-ssl',
            'pipeline',
            'render',
            'rendered-html',
            'pipeline-include-failed',
            'pipeline-include-skipped',
            'resume',
            'retry-challenge',
            'same-domain',
            'same-final-host',
            'save-body',
            'save-rendered-html',
            'screenshot',
            'skip-challenge-pages',
            'skip-identity-provider-final-urls',
            'solr',
            'stay-under-start-path',
            'strip-final-url-query-params',
            'until-success',
            'use-cookie-jar',
            'dry-run',
            'failed-jobs',
            'all',
            'force',
            'print-command',
            'training-ready',
            'remove-profile',
            'no-headless',
            'allow-assets',
            'no-html',
            'once',
            'stop-on-error',
            'send',
            'fail-on-high',
            'active-only',
            'strict',
            'respect-robots',
            'save-html',
            'whole-html',
            'html',
            'no-images',
            'validate',
        ];
    }
}
