<?php

declare(strict_types=1);

namespace Mnb\ScraperKit\Console;

/**
 * Central command metadata for the Symfony Console front end.
 */
final class CommandRegistry
{
    /** @return array<string,string> command name => description */
    public static function commands(): array
    {
        return [
            'crawl' => 'Crawl one URL/site with safety rules, presets, common data, and optional professional pipeline.',
            'http:test' => 'Test the HTTP engine, redirects, headers, and challenge/protection detection.',
            'bulk:crawl' => 'Crawl a URL list with gaps, pauses, checkpoint state, and resume support.',
            'url:process' => 'Process URLs sequentially with retry, method ladder, backoff, checkpoint, and resume.',
            'robots:test' => 'Inspect robots.txt decision for one URL.',
            'encoding:test' => 'Fetch one URL and report detected/converted encoding.',
            'common:extract' => 'Extract common structured data patterns from one URL.',
            'common:types' => 'List supported common data types and extraction profiles.',
            'report:failed' => 'Create failed/skipped URL diagnostics from crawl JSON.',
            'export:failed' => 'Export failed/skipped URL diagnostics as JSON, CSV, or XML.',
            'report:summary' => 'Generate professional job summary reports as HTML, JSON, CSV, or XML.',
            'bundle:create' => 'Create a ZIP bundle containing exports, reports, manifests, and logs.',
            'pipeline:run' => 'Run the professional crawl pipeline on crawl JSON.',
            'retry:failed' => 'Create a retry URL list from failed crawl pages.',
            'export:records' => 'Export pipeline records to JSON, CSV, XML, or HTML.',
            'export:validation' => 'Export validation issues from pipeline output as JSON, CSV, or XML.',
            'validate:records' => 'Validate records using required fields.',
            'job:summary' => 'Show job manifest, crawl summary, and pipeline summary.',
            'job:run' => 'Run a crawl/bulk job from a JSON job configuration.',
            'source:discover' => 'Discover safer source candidates such as sitemap, feeds, robots, and well-known endpoints.',
            'source:sitemap' => 'Read sitemap.xml or sitemap index and export crawlable URLs.',
            'source:rss' => 'Read RSS/Atom feed and export normalized records/URLs.',
            'source:csv' => 'Read crawl URLs from CSV using a configurable URL column.',
            'source:json' => 'Read crawl URLs from JSON using a dot path such as items.*.url.',
            'source:api' => 'Fetch a JSON API endpoint and extract URLs using a dot path.',
            'source:urls' => 'Export a URL list from source connector JSON output.',
            'plos:journals' => 'List known PLOS journals, API names, homepages, and feed candidates.',
            'plos:search' => 'Use the PLOS Search API and return normalized article records.',
            'plos:feed' => 'Fetch a PLOS journal RSS/Atom feed and normalize article records.',
            'plos:urls' => 'Export article/PDF/XML/DOI URLs from PLOS API results for bulk workflows.',
            'elsevier:journals' => 'Show Elsevier/ScienceDirect source connector catalog and API command hints.',
            'elsevier:search' => 'Search ScienceDirect API using an Elsevier API key.',
            'elsevier:metadata' => 'Fetch ScienceDirect article metadata by DOI or PII.',
            'elsevier:doi' => 'Shortcut for ScienceDirect article metadata by DOI.',
            'elsevier:serial' => 'Fetch Elsevier serial title metadata by ISSN.',
            'elsevier:urls' => 'Export article/DOI/API URLs from ScienceDirect search results.',
        ];
    }

    /** @return list<string> */
    public static function optionNames(): array
    {
        return [
            'allow-path',
            'api-base',
            'api-key',
            'api-key-in-query',
            'article-api-base',
            'attempts',
            'backoff',
            'backoff-multiplier',
            'batch-pause',
            'batch-size',
            'browser',
            'browser-profile',
            'checkpoint',
            'common-data',
            'crawl',
            'common-profile',
            'common-type',
            'content',
            'url-column',
            'path',
            'max-sitemaps',
            'delimiter',
            'crawl',
            'cookie-jar',
            'count',
            'dedupe-key',
            'delay',
            'delay-ms',
            'depth',
            'do-not-skip-challenge-pages',
            'do-not-skip-idp',
            'do-not-stop-on-challenge',
            'doi',
            'engine',
            'extract-preset',
            'fail-on-challenge',
            'feed-url',
            'field',
            'field-map',
            'fields',
            'format',
            'include-logs',
            'include-manifest',
            'fq',
            'gap',
            'gap-ms',
            'header',
            'http-engine',
            'id',
            'ignore-robots',
            'include-failed',
            'include-headers',
            'include-html',
            'include-logs',
            'include-manifest',
            'include-page',
            'include-skipped',
            'inst-token',
            'insttoken',
            'issn',
            'job-dir',
            'journal',
            'json',
            'max',
            'max-attempts',
            'max-delay-seconds',
            'max-depth',
            'max-pages',
            'max-redirects',
            'max-runtime-seconds',
            'method',
            'methods',
            'min-quality',
            'network',
            'network-profile',
            'no-api-key-required',
            'no-cookie-jar',
            'no-preset-records',
            'no-robots',
            'no-verify-ssl',
            'only-type',
            'output',
            'output-dir',
            'pause-every-seconds',
            'pause-seconds',
            'pipeline',
            'pipeline-dedupe-key',
            'pipeline-field-map',
            'pipeline-format',
            'pipeline-include-failed',
            'pipeline-include-skipped',
            'pipeline-min-quality',
            'pipeline-output',
            'pipeline-profile',
            'pipeline-required-field',
            'preset',
            'profile',
            'query',
            'required-field',
            'resume',
            'retry-challenge',
            'retry-delay',
            'retry-delay-seconds',
            'retry-status',
            'rows',
            'rule',
            'rules-file',
            'same-domain',
            'same-final-host',
            'save-body',
            'serial-api-base',
            'skip-challenge-pages',
            'skip-final-host',
            'skip-identity-provider-final-urls',
            'skip-url',
            'solr',
            'sort',
            'start',
            'stay-under-start-path',
            'stop-file',
            'strip-final-param',
            'strip-final-url-query-params',
            'success-status',
            'timeout',
            'timeout-seconds',
            'type',
            'until-success',
            'use-cookie-jar',
            'user-agent',
            'view',
        ];
    }

    /** @return list<string> */
    public static function valueLessOptions(): array
    {
        return [
            'api-key-in-query',
            'common-data',
            'crawl',
            'do-not-skip-challenge-pages',
            'do-not-skip-idp',
            'do-not-stop-on-challenge',
            'fail-on-challenge',
            'ignore-robots',
            'include-failed',
            'include-headers',
            'include-html',
            'include-logs',
            'include-manifest',
            'include-page',
            'include-skipped',
            'json',
            'no-api-key-required',
            'no-cookie-jar',
            'no-preset-records',
            'no-robots',
            'no-verify-ssl',
            'pipeline',
            'pipeline-include-failed',
            'pipeline-include-skipped',
            'resume',
            'retry-challenge',
            'same-domain',
            'same-final-host',
            'save-body',
            'skip-challenge-pages',
            'skip-identity-provider-final-urls',
            'solr',
            'stay-under-start-path',
            'strip-final-url-query-params',
            'until-success',
            'use-cookie-jar',
        ];
    }
}
